package edu.uclm.esi.fakeaccountsbe.tests;

// Generated by Selenium IDE
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.TestMethodOrder;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;

import org.junit.jupiter.api.MethodOrderer.OrderAnnotation;


@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@TestMethodOrder(OrderAnnotation.class)
public class RegistroTest {

	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor jsExecutor;


	@BeforeAll //@AfterAll
	public void setUp() {

		System.setProperty("webdriver.chrome.driver", "C:/Users/Enrique/Desktop/webdriver/testingTECWEB/chromedriver-win64/chromedriver.exe");  

		ChromeOptions options = new ChromeOptions();
		options.setBinary("C:/Users/Enrique/Desktop/webdriver/testingTECWEB/chrome-win64/chrome.exe"); 
		options.addArguments("--remote-allow-origins=*");

		driver = new ChromeDriver(options);
		new WebDriverWait(driver, Duration.ofSeconds(3));

		jsExecutor = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();

	}

	@AfterAll
	public void tearDown() {
		driver.quit();
	}

	@Test @Order(1)
	public void testRegistroCorrecto() {
		driver.get("https://alarcosj.esi.uclm.es/examplesfortesting/");
		this.pausa(1000);

		WebElement botonAngular = driver.findElement(By.xpath("/html/body/div[1]/div/a[1]"));
		botonAngular.click();

		this.pausa(1000);

		WebElement menuRegistrarse = driver.findElement(By.xpath("/html/body/app-root/div/header/nav/ul/li[2]/a"));
		menuRegistrarse.click();

		this.pausa(1000);

		WebElement inputNombre = driver.findElement(By.xpath("/html/body/app-root/div/main/app-register/form/div[1]/input"));
		WebElement inputEmail = driver.findElement(By.xpath("/html/body/app-root/div/main/app-register/form/div[2]/input"));
		WebElement inputPwd1 = driver.findElement(By.xpath("/html/body/app-root/div/main/app-register/form/div[3]/input"));
		WebElement inputPwd2 = driver.findElement(By.xpath("/html/body/app-root/div/main/app-register/form/div[4]/input"));
		WebElement botonRegistrarse = driver.findElement(By.xpath("/html/body/app-root/div/main/app-register/form/div[5]/button"));

		inputNombre.sendKeys("alex");
		inputEmail.sendKeys("alex@alex.com");
		inputPwd1.sendKeys("Alex1234");
		inputPwd2.sendKeys("Alex1234");
		botonRegistrarse.click();

		this.pausa(1000);

		String url = driver.getCurrentUrl();
		assertEquals("https://alarcosj.esi.uclm.es/examplesfortesting/angular/login", url);

		//WebElement etiqueta = driver.findElement(By.xpath("/html/body/app-root/div/main/app-login/h2"));
		//assertEquals("Login", etiqueta.getText()) 
	}

	@Test @Order(2)
	public void testLoginCorrecto() {
		WebElement cajaNombre = driver.findElement(By.xpath("/html/body/app-root/div/main/app-login/form/div[1]/input"));
		WebElement cajaPwd = driver.findElement(By.xpath("/html/body/app-root/div/main/app-login/form/div[2]/input"));

		cajaNombre.sendKeys("alex");
		cajaPwd.sendKeys("Alex1234");

		WebElement botonLogin = driver.findElement(By.xpath("/html/body/app-root/div/main/app-login/form/div[3]/button"));
		botonLogin.click();

		this.pausa(1000);

		String url = driver.getCurrentUrl();

		assertEquals("https://alarcosj.esi.uclm.es/examplesfortesting/angular/celebration", url);
	}


	private void pausa(int i) {
		try {
			Thread.sleep(i);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
	}
}